name: Ubuntu

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-ubuntu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        comp: [gpp, clangpp]
        cfg: [debug, release]
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.29.x"

      - name: Apt update
        run: sudo apt-get update

      - name: Install toolchains
        run: sudo apt-get install -y ninja-build g++ clang

      - name: Configure
        run: cmake --preset linux-${{ matrix.comp }}-23-${{ matrix.cfg }}

      - name: Build
        run: cmake --build --preset build-linux-${{ matrix.comp }}-23-${{ matrix.cfg }}

      - name: Test
        run: ctest --preset test-linux-${{ matrix.comp }}-23-${{ matrix.cfg }}
        
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-logs-${{ matrix.comp }}-${{ matrix.cfg }}
          path: |
            build/**/Testing/**
            **/CMakeFiles/CMakeOutput.log
            **/CMakeFiles/CMakeError.log
